window.addEventListener("load", function () {
    //collect input values
    var Name1 = localStorage.getItem("Name");
    var profess = localStorage.getItem("Profession");
    var mobile = localStorage.getItem("Phone");
    var Email = localStorage.getItem("Email");
    var Address = localStorage.getItem("Address");
    var Skills = localStorage.getItem("skills");
    var languages = localStorage.getItem("languages");
    var About = localStorage.getItem("aboutMe");
    var Experience = localStorage.getItem("Experience");
    var uniYear = localStorage.getItem("uniYear");
    var uniName = localStorage.getItem("uniName");
    var collYear = localStorage.getItem("collYear");
    var collName = localStorage.getItem("collName");
    var schoolYear = localStorage.getItem("schYear");
    var schoolName = localStorage.getItem("schName");
    var Hobby = localStorage.getItem("Hobbies");
    var profilepicture = localStorage.getItem("profilepicture");
    var firstName = document.getElementById("firstName");
    firstName.textContent = Name1;
    var profession = document.getElementById("profession");
    profession.textContent = profess;
    var resumeTel = document.getElementById("resumeTel");
    resumeTel.textContent = mobile;
    var resumeMail = document.getElementById("resumeMail");
    resumeMail.textContent = Email;
    var resumeHome = document.getElementById("resumeHome");
    resumeHome.textContent = Address;
    var resumeSkills = document.getElementById("resumeSkills");
    resumeSkills.textContent = Skills;
    var resumeLang = document.getElementById("resumeLang");
    resumeLang.textContent = languages;
    var resumeAbout = document.getElementById("resumeAbout");
    resumeAbout.textContent = About;
    var resumeExp = document.getElementById("resumeExp");
    resumeExp.textContent = Experience;
    var uniYear1 = document.getElementById("uniYear1");
    uniYear1.textContent = uniYear;
    var uniName1 = document.getElementById("uniName1");
    uniName1.textContent = uniName;
    var collYear2 = document.getElementById("collYear2");
    collYear2.textContent = collYear;
    var collName2 = document.getElementById("collName2");
    collName2.textContent = collName;
    var schYear3 = document.getElementById("schYear3");
    schYear3.textContent = schoolYear;
    var schName3 = document.getElementById("schName3");
    schName3.textContent = schoolName;
    var resmeHobby = document.getElementById("resumeHobby");
    resmeHobby.textContent = Hobby;
    var profile_picture = document.getElementById("profile-picture");
    profile_picture.src = profilepicture;
});
var button_Skills = document.getElementById("toggle-skills");
var Skills = document.getElementById("SKILLS");
button_Skills.addEventListener('click', function () {
    Skills.classList.toggle("hide");
});
var edit = document.getElementById("editable-resume");
edit.addEventListener('click', function () {
    window.history.back();
});
